# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: AppleCIDR Labbing
tagline: Just an idiot that loves networking
description: If it ain't broke, break it until you can fix it.

mainNav:
  - name: "ContainerLab"
    link: /ContainerLab/intro
  - name: "Netbox"
    link: /Netbox/certInstall
  - name: "Ansible"
    link: /ansible/install
  - name: "netmiko"
    link: /netmiko/configBackup
  - name: "Labs"
    link: /ContainerLab/labs/labs

clabnav:
  - name: "Home"
    link: /
  - name: "Prerequisites"
    link: /ContainerLab/prerequisites
  - name: "Install"
    link: /ContainerLab/install
  - name: "Quick Start"
    link: /ContainerLab/quick_start
  - name: "VS Code Extension"
    link: /ContainerLab/vscodeext
