title: AppleCIDR Labbing
tagline: Just an idiot that loves networking
description: If it ain't broke, break it until you can fix it.

mainNav:
  - name: "ContainerLab"
    link: /ContainerLab/intro
  - name: "Ansible"
    link: /ansible/install
  - name: "netmiko"
    link: /netmiko
  - name: "Labs"
    link: /ContainerLab/labs/labs

clabnav:
  - name: "Home"
    link: /
  - name: "Prerequisites"
    link: /ContainerLab/prerequisites
  - name: "Install"
    link: /ContainerLab/install
  - name: "Quick Start"
    link: /ContainerLab/quick_start
  - name: "VS Code Extension"
    link: /ContainerLab/vscodeext
